name: Django CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Run Tests
      run: |
        # Use 'docker compose' instead of 'docker-compose'
        docker compose build backend
        docker compose run --rm backend python manage.py test api
        
        docker compose -f path/to/your/docker-compose.yml build backend